// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1_pnccKm2qAfn8c8yEMlXWgxY4nGdxUU',
    appId: '1:549196398010:web:bf3588447bdf577f377183',
    messagingSenderId: '549196398010',
    projectId: 'sandlyn',
    authDomain: 'sandlyn.firebaseapp.com',
    storageBucket: 'sandlyn.firebasestorage.app',
    measurementId: 'G-L2EVBLFZHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7BnlxKdKC0aWwh5FkWemAD47zwk0dvOw',
    appId: '1:549196398010:android:aa7e21b5ce730212377183',
    messagingSenderId: '549196398010',
    projectId: 'sandlyn',
    storageBucket: 'sandlyn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHqwRhOwGLRlm5or5mwTB7gQdp0mZ8m44',
    appId: '1:549196398010:ios:504a801bbc620f33377183',
    messagingSenderId: '549196398010',
    projectId: 'sandlyn',
    storageBucket: 'sandlyn.firebasestorage.app',
    iosBundleId: 'com.example.sendly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHqwRhOwGLRlm5or5mwTB7gQdp0mZ8m44',
    appId: '1:549196398010:ios:504a801bbc620f33377183',
    messagingSenderId: '549196398010',
    projectId: 'sandlyn',
    storageBucket: 'sandlyn.firebasestorage.app',
    iosBundleId: 'com.example.sendly',
  );
}
